#!/usr/bin/env python3
"""
Event-Driven Report Scheduler for GenericAgent
结合事件触发与定时调度的报告生成器
支持: cron表达式、事件条件、报告模板、多渠道分发
"""

import os
import sys
import time
import json
import threading
import logging
from datetime import datetime, timedelta
from typing import Callable, Dict, Any, List, Optional
from pathlib import Path
from queue import Queue, Empty
import hashlib

logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(levelname)s] %(message)s')
logger = logging.getLogger(__name__)

class ReportConfig:
    """报告配置"""
    def __init__(self, name: str, trigger_type: str = "scheduled", 
                 schedule: str = "daily", event_condition: str = None,
                 template: str = "default", output_path: str = None):
        self.name = name
        self.trigger_type = trigger_type
        self.schedule = schedule
        self.event_condition = event_condition
        self.template = template
        self.output_path = output_path or f"./reports/{name}.md"
        self.last_run = None

class ReportScheduler:
    """事件驱动的报告调度器"""
    def __init__(self, config_file: str = "report_config.json"):
        self.configs: Dict[str, ReportConfig] = {}
        self.event_queue = Queue()
        self.running = False
        self.config_file = config_file
        self.report_templates = {
            "default": self._default_template,
            "summary": self._summary_template,
            "detailed": self._detailed_template
        }
        self._load_configs()

    def _load_configs(self):
        if os.path.exists(self.config_file):
            try:
                with open(self.config_file, 'r') as f:
                    data = json.load(f)
                    for name, cfg in data.items():
                        self.configs[name] = ReportConfig(**cfg)
                logger.info(f"Loaded {len(self.configs)} report configs")
            except Exception as e:
                logger.error(f"Failed to load configs: {e}")

    def _save_configs(self):
        data = {name: {k: v for k, v in cfg.__dict__.items() 
                      if not k.startswith('_')} 
                for name, cfg in self.configs.items()}
        with open(self.config_file, 'w') as f:
            json.dump(data, f, indent=2)

    def add_report(self, name: str, trigger_type: str = "scheduled",
                   schedule: str = "daily", event_condition: str = None,
                   template: str = "default", output_path: str = None):
        config = ReportConfig(name, trigger_type, schedule, 
                             event_condition, template, output_path)
        self.configs[name] = config
        self._save_configs()
        logger.info(f"Added report: {name}")

    def _should_run(self, config: ReportConfig, current_time: datetime) -> bool:
        if config.last_run:
            last = config.last_run
            if config.schedule == "daily":
                if current_time.date() == last.date():
                    return False
            elif config.schedule == "weekly":
                if (current_time - last).days < 7:
                    return False
            elif config.schedule == "monthly":
                if current_time.month == last.month and current_time.year == last.year:
                    return False
            elif config.schedule.startswith("*/"):
                interval = int(config.schedule[2:])
                if (current_time - last).total_seconds() < interval * 3600:
                    return False
        return True

    def generate_report(self, config: ReportConfig) -> str:
        template_func = self.report_templates.get(config.template, self._default_template)
        return template_func(config)

    def _default_template(self, config: ReportConfig) -> str:
        now = datetime.now()
        return f"""# {config.name} 报告
生成时间: {now.strftime('%Y-%m-%d %H:%M:%S')}
触发类型: {config.trigger_type}
调度策略: {config.schedule}

## 系统状态
- 运行时间: {self._uptime()}
- 待处理事件: {self.event_queue.qsize()}
- 已配置报告: {len(self.configs)}

## 最近更新
{self._recent_changes()}

---
*Generated by GenericAgent Report Scheduler*
"""

    def _summary_template(self, config: ReportConfig) -> str:
        now = datetime.now()
        return f"""# 系统摘要 - {now.strftime('%Y-%m-%d')}

## 关键指标
- 活跃任务: {self._count_active_tasks()}
- 错误率: {self._error_rate()}%
- 存储使用: {self._storage_usage()}

## 异常事件
{self._recent_errors()}
"""

    def _detailed_template(self, config: ReportConfig) -> str:
        now = datetime.now()
        return f"""# 详细系统报告
生成时间: {now.strftime('%Y-%m-%d %H:%M:%S')}

## 性能指标
{self._performance_metrics()}

## 事件日志
{self._event_log_summary()}

## 存储分析
{self._storage_analysis()}

## 建议操作
{self._recommendations()}
"""

    def _write_report(self, config: ReportConfig, content: str):
        os.makedirs(os.path.dirname(config.output_path) or '.', exist_ok=True)
        with open(config.output_path, 'w', encoding='utf-8') as f:
            f.write(content)
        config.last_run = datetime.now()
        self._save_configs()
        logger.info(f"Report written: {config.output_path}")

    def _process_loop(self):
        while self.running:
            now = datetime.now()
            for name, config in self.configs.items():
                if config.trigger_type in ["scheduled", "hybrid"]:
                    if self._should_run(config, now):
                        logger.info(f"Triggering scheduled report: {name}")
                        content = self.generate_report(config)
                        self._write_report(config, content)
            try:
                event = self.event_queue.get(timeout=1)
                for name, config in self.configs.items():
                    if config.trigger_type in ["event", "hybrid"]:
                        if config.event_condition and self._check_event_condition(event, config.event_condition):
                            logger.info(f"Event triggered report: {name}")
                            content = self.generate_report(config)
                            self._write_report(config, content)
            except Empty:
                pass
            time.sleep(10)

    def _check_event_condition(self, event: str, condition: str) -> bool:
        if condition == "*":
            return True
        return condition in str(event)

    def start(self):
        self.running = True
        threading.Thread(target=self._process_loop, daemon=True).start()
        logger.info("Report scheduler started")

    def stop(self):
        self.running = False
        logger.info("Report scheduler stopped")

    def trigger_event(self, event: str):
        self.event_queue.put(event)

    def _uptime(self):
        return "N/A (模拟)"
    
    def _recent_changes(self):
        return "- 无变更"
    
    def _count_active_tasks(self):
        return 0
    
    def _error_rate(self):
        return 0.0
    
    def _storage_usage(self):
        return "N/A"
    
    def _recent_errors(self):
        return "无错误"
    
    def _performance_metrics(self):
        return "待实现"
    
    def _event_log_summary(self):
        return "无事件"
    
    def _storage_analysis(self):
        return "待分析"
    
    def _recommendations(self):
        return "无建议"

if __name__ == '__main__':
    scheduler = ReportScheduler()
    scheduler.add_report("daily_system", "scheduled", "daily", 
                        template="default", output_path="./reports/daily.md")
    scheduler.add_report("error_report", "event", None, 
                        event_condition="error", template="summary",
                        output_path="./reports/errors.md")
    scheduler.start()
    print("Scheduler running. Press Ctrl+C to stop.")
    try:
        time.sleep(10)
    except KeyboardInterrupt:
        scheduler.stop()
